### PR TITLE
For #1199

### PR DESCRIPTION
**Pull request by mugitty**
Note, this PR is associated with https://github.com/geneontology/go-site/pull/2207

### CODE REVIEW

**Comment by dustine32** [comment]
@mugitty Change here is to `rsync` a `aggregate-rule-violation-report.md` file but where is this file generated? I don't see the command to generate in the Jenkinsfile. Does this line need to be updated too?
https://github.com/geneontology/pipeline/blob/995bd712499a38a3bb7180578016461500bef1e0/Jenkinsfile#L762

**Comment by mugitty** [comment]
aggregate-rule-violation-report.md is an additional file that is generated by combined_assigned_by.py

**Comment by dustine32** [comment]
@mugitty Oh I see. Filename `aggregate-rule-violation-report.md` is [hard-coded](https://github.com/geneontology/go-site/pull/2207/files#diff-72b6698f3eaf7d262bc1f215afb5932dde19d088df6c70c339caf6036499aaa9R265) in `combined_assigned_by.py`.

This works but it might be nicer to parameterize that new output filename so that it's explicitly mentioned in the `Jenkinsfile`. I'll let @kltm decide whether that's really required.

**Comment by kltm** [comment]
When is the file going to start being produced and how? I want to make sure there is no lag so that `rsync` does not/cannot fail here. Ideally, the file would be produced and in the branches before the move itself was updated.

**Comment by mugitty** [comment]
@kltm , It is already being produced in https://build.geneontology.org/job/geneontology/job/pipeline/job/issue-go-site-2093-metadata/
https://github.com/geneontology/go-site/pull/2207#issuecomment-1841635784 has to go in first.

**Comment by kltm** [comment]
@mugitty it's not being produced on `master`, `snapshot`, or `release`, which are the ones I care about here.

**Comment by mugitty** [comment]
@kltm , I will update on master

**Comment by kltm** [comment]
@mugitty To clarify, the `go-site` merge needs to happen before the `pipeline` merge.

**Pull request closed without merging**
