### PR TITLE
Issue go site 2093 metadata

### PR DESCRIPTION
**Pull request by mugitty**
For #1199 copy aggregate markdown file to reports directory

### CODE REVIEW

**Comment by kltm** [comment]
geneontology/go-site#2093 and geneontology/go-site#1199 ?

**Comment by kltm** [comment]
@mugitty There's a bunch of changes here that need to be reverted: the only change from `master` should be the file copy.

**Comment by mugitty** [comment]
@kltm, I copied over master and added change

**Comment by kltm** [comment]
Talked to @mugitty , looks like the bumped file is covered by a regexp elsewhere.

**Pull request merged**
