### PR TITLE
Using the new downloader script in go-site to download and then organ…

### PR DESCRIPTION
**Pull request by dougli1sqrd**
…ize the gaf files

### CODE REVIEW

**Comment by dougli1sqrd** [comment]
@kltm okay sources are being removed now.

**Comment by kltm** [comment]
Add gaferencer, downloads, and sort them into piles
For #27  #103

**Comment by kltm** [comment]
@dougli1sqrd no longer WIP?

**Comment by dougli1sqrd** [comment]
Yes, that's correct.

**Comment by kltm** [comment]
Discussed with @dougli1sqrd in person--should work.

**Pull request merged**
