### PR TITLE
setting python command

### PR DESCRIPTION
**Pull request by dougli1sqrd**

### CODE REVIEW

**Comment by kltm** [comment]
@dougli1sqrd I'm not sure why you're overwriting a variable with itself?

**Comment by dougli1sqrd** [comment]
ah I see, I'm still understanding the Jenkinsfile stuff. Do I not need to redefine env variables in the `withenv` declaration? If it's just set up above, it'll just inherit? I guess the other variables are doing that.

**Comment by kltm** [comment]
I believe what you want actually looks like the current state: a locally scoped variable for changing the python command.

**Comment by dougli1sqrd** [comment]
Ah thanks! That makes more sense.

**Comment by dougli1sqrd** [comment]
Should we merge this then?

**Comment by kltm** [comment]
Let's clear the current issues with downloads first--it's been a week since success on `snapshot`.

**Comment by dougli1sqrd** [comment]
No longer needed.

**Pull request closed without merging**
