### PR TITLE
Issue 200 ontology override

### PR DESCRIPTION
**Pull request by dougli1sqrd**
https://github.com/geneontology/pipeline/issues/200

### CODE REVIEW

**Comment by kltm** [comment]
`VALIDATION_ONTOLOGY_URL="http://skyhook.berkeleybop.org/$BRANCH_NAME/ontology/go.json"` is going to need to be the actual branch name, not the variable.
See: https://github.com/geneontology/pipeline/blob/d566cff20b950c6aacf897bfa42ddf3aabdd405c/Jenkinsfile#L92
In fact, it's probably better to put it up here in a new section: https://github.com/geneontology/pipeline/blob/d566cff20b950c6aacf897bfa42ddf3aabdd405c/Jenkinsfile#L86

**Comment by dougli1sqrd** [comment]
oh how come it can't be parameterized by branch name? But otherwise, that seems fine. What would you call the new section? Should we also move the `RESOURCE_GROUPS` and `DATASET_EXCLUDES` into the new "megastep" variables?

**Comment by kltm** [comment]
I believe that's just the way that section works (although I may be wrong or it may have changed). Whatever the comment section is named is fine--I can always change things later on in master if it needs it. I'd prefer not to churn the metadata section, but that new grouping makes sense.

**Comment by dougli1sqrd** [comment]
@kltm I just updated this.

**Comment by kltm** [comment]
Okay, revisiting. I think this looks good and unlikely to cause any issues (unless something that we forgot is using `ONTOLOGY` under the hood.

**Pull request merged**
