### PR TITLE
Issue 115 dockerize megastep

### PR DESCRIPTION
**Pull request by dougli1sqrd**
This is a new PR from my own fork. This should be what master looks like once we want to add dockerization to the mega-make step. The other branch `grouped_gaferencer_test` is tuned to be a test of dockerization, and not expected to be very mergable. 

As always, sorry about the formatting :(.

### CODE REVIEW

**Comment by dougli1sqrd** [comment]
That makes sense. If we supplied a volume map that could work, but we don't know the location that Jenkins will be working in beforehand:
```
args "-v $WORKSPACE/pipeline/data/:/wherever/jenkins/operates"
```
It's possible we could use a known location within the image to then link to the known location or something? That way we can still map the on-the-fly location to the known location which would then be seen by the outside?

Or if something fails running in the image, can we do a data dump to a known location before we bail somehow?

**Comment by kltm** [comment]
As a first pass, let's just follow the pattern used out by the Solr loader; we can then worry about resolving variables (e.g. WORKSPACE) in the arg parameters.

**Comment by kltm** [comment]
So this will drop into a megastep/ directory?

**Comment by dougli1sqrd** [comment]
Yeah this puts the gpads in the data/gpads/ directory, and then puts the entire target directory is put in data/megastep/. 

I noticed though that in golr we don't specify a source directory (on the Jenkins host)? I looked for that in the docs, but I couldn't find what the default value for source is when not specified.

**Comment by dougli1sqrd** [comment]
We could lightly modify this and run as a full test, as this has not been run as well.

**Comment by kltm** [comment]
@dougli1sqrd You should be able to run/test this locally, right?

**Pull request merged**
